import {
  ArrowDownLeft,
  ArrowDownToLine,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Bell,
  Bookmark,
  Briefcase,
  CalendarClock,
  Camera,
  Captions,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleDot,
  Clapperboard,
  Clock,
  CodeXml,
  FileCheck,
  HandCoins,
  IdCard,
  ImageIcon,
  ImageUp,
  Inbox,
  LayoutDashboard,
  Lock,
  LogOut,
  Megaphone,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  PackageCheck,
  Palette,
  Pin,
  PinOff,
  Play,
  Plus,
  Receipt,
  RefreshCw,
  Repeat,
  RotateCcw,
  ScanFace,
  Search,
  Send,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Star,
  Sun,
  Tag,
  Timer,
  Trash2,
  TrendingUp,
  UserRound,
  Video,
  Volume2,
  VolumeX,
  Wallet,
  X,
  Zap,
} from "lucide-react";

const registry = {
  "arrow-down-left": ArrowDownLeft,
  "arrow-down-to-line": ArrowDownToLine,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "badge-check": BadgeCheck,
  bell: Bell,
  bookmark: Bookmark,
  briefcase: Briefcase,
  "calendar-clock": CalendarClock,
  camera: Camera,
  captions: Captions,
  check: Check,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-dot": CircleDot,
  clapperboard: Clapperboard,
  clock: Clock,
  "code-xml": CodeXml,
  "file-check": FileCheck,
  "hand-coins": HandCoins,
  "id-card": IdCard,
  image: ImageIcon,
  "image-up": ImageUp,
  inbox: Inbox,
  "layout-dashboard": LayoutDashboard,
  lock: Lock,
  "log-out": LogOut,
  megaphone: Megaphone,
  "message-circle": MessageCircle,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  "package-check": PackageCheck,
  palette: Palette,
  pin: Pin,
  "pin-off": PinOff,
  play: Play,
  plus: Plus,
  receipt: Receipt,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  "rotate-ccw": RotateCcw,
  "scan-face": ScanFace,
  search: Search,
  send: Send,
  settings: Settings,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  star: Star,
  sun: Sun,
  tag: Tag,
  timer: Timer,
  "trash-2": Trash2,
  "trending-up": TrendingUp,
  "user-round": UserRound,
  video: Video,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  wallet: Wallet,
  x: X,
  zap: Zap,
};

// "material-symbols:star-rounded" in the design is a single filled rounded
// star used only for ratings — approximated here with lucide's Star filled,
// since the exact glyph isn't load-bearing.
export default function Icon({ icon, size = 16, className = "", style, ...rest }) {
  const name = (icon || "").replace(/^lucide:/, "").replace(/^material-symbols:star-rounded$/, "star");
  const Cmp = registry[name];
  if (!Cmp) return null;
  const filled = icon === "material-symbols:star-rounded";
  return (
    <Cmp
      size={size}
      className={className}
      strokeWidth={2}
      style={style}
      fill={filled ? "currentColor" : "none"}
      {...rest}
    />
  );
}
